import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const SUPPORTED_LOCALES = ["en", "hi", "kn"] as const;
type AppLocale = (typeof SUPPORTED_LOCALES)[number];

function isAppLocale(locale: string): locale is AppLocale {
  return (SUPPORTED_LOCALES as readonly string[]).includes(locale);
}

export const metadata: Metadata = {
  title: "vanitha",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const safeLocale: AppLocale = isAppLocale(locale) ? locale : "en";

  setRequestLocale(safeLocale);

  const messages = await getMessages();

  return (
    <html lang={safeLocale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}